# Generated by Django 3.2 on 2022-07-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_deal', models.CharField(choices=[('HOT DEALS', 'HOt Deals'), ('NEW ARRIVALS', 'New Arrivals'), ('SPECIAL OFFERS', 'Special Offers'), ('TOP RATED', 'Top Rated'), ('BEST SELLER', 'Best Seller')], max_length=100)),
                ('sale', models.IntegerField()),
                ('brand', models.CharField(max_length=200)),
                ('discount', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/slider/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
