# Generated by Django 3.2 on 2022-07-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220715_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model_Name',
            new_name='sku',
        ),
    ]
